schema_version: 1

context:
  name: opentelemetry-instrumentation-qdrant
  version: "0.62.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/opentelemetry_instrumentation_qdrant-${{ version }}.tar.gz
  sha256: 367e11e4bc88e3cb86eef20222a4ff3555270e1da3cf0e3265867881b5d5762d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - opentelemetry-api >=1.38.0,<2.0.0
    - opentelemetry-instrumentation >=0.59b0
    - opentelemetry-semantic-conventions >=0.59b0
    - opentelemetry-semantic-conventions-ai >=0.5.1,<0.6.0
  run_constraints:
    - qdrant-client >=1.9.1,<2.0.0

tests:
  - requirements:
      run:
        - python ${{ python_min }}.*
        - qdrant-client
        - pip
    script:
      - python -c "import opentelemetry.instrumentation.qdrant"
      - pip check

about:
  summary: OpenTelemetry Qdrant instrumentation
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://www.traceloop.com/openllmetry
  repository: https://github.com/traceloop/openllmetry
  documentation: https://www.traceloop.com/docs/openllmetry/introduction

extra:
  recipe-maintainers:
    - timkpaine
